name: RIC Workflow

on:
  push:
  pull_request:

jobs:
  linux-gcc:
    name: ${{ matrix.mode }}

    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        mode:
        - basic_test
    env:
      MODE: ${{ matrix.mode }}

    steps:

    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 0
        submodules: true
          
    - name: Install dependencies
      run: 
        sudo apt-get install tclsh cmake

    - name: RIC_Ubuntu
      if: matrix.mode == 'basic_test' 
      shell: bash
      run: |
        cd Device_Modeling/
        make
        cd -
        cd Device_Modeling/src && mkdir build && cd build && cmake .. && make && ./Device_Modeling_test

       

 
